Description of progmeter
Home > source-code > progmeter.m
progmeter
PURPOSE
SYNOPSIS
function progmeter(i,n,w)
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
mgmotion MGMOTION - Calculate various motion features from a video file
mgmotionhistory mgmotionhistory(vidfile,nframe,type,starttime,endtime)
mgreadsegment function out = mgreadsegment(varargin)
mgvideoadjust function mg = mgvideoadjust(varargin)
mgvideocrop function mg = mgvideocrop(varargin)
mgvideofilter mg = mgvideofilter(varargin)
mgvideogram function mg = mgvideogram(varargin)
mgvideomagnify mgvideomagnify magnifies a video with small variations, the magnified
mgvideorotate function mg = mgvideocrop(varargin)
mgvideosample function mg = mgvideosample(varargin)
SOURCE CODE
function progmeter(i,n,w)
  disp(' ');
if nargin<3,
    w = 1;
end
if i==1
  disp(' ');
    fwrite(1,sprintf('process in progress:  \n'));
    return;
elseif ischar(i)
  disp(' ');
    fwrite(1,sprintf('%s\n',i));
    fwrite(1,sprintf('00%%'));
    return;
end
if mod(i,w*n/100) <= mod(i-1,w*n/100),
  disp(' ');
    fwrite(1,sprintf('\b\b\b'));
    fwrite(1,sprintf('%2d%%', round(100*i/n)));
end
if i==n,
  disp(' ');
  fprintf(1,'\n');
end